/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devpos.Transaksi;

import devpos.Barang.*;
import devpos.Kategori.*;
import devpos.models.Barang;
import devpos.models.Kategori;
import devpos.models.Transaksi;
import java.awt.Color;
import java.awt.Font;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gunawan
 */
public class TransaksiView extends javax.swing.JFrame {
    public static String globalId;
    public static String inputNameEdit;
    public static String inputHargaEdit;
    public static String inputKodeKategoriEdit;
    
    /**
     * Creates new form tabel
     */
    public TransaksiView() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        
        tableKategori.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tableKategori.getTableHeader().setOpaque(false);
        tableKategori.getTableHeader().setBackground(new Color(0,41,121));
        tableKategori.getTableHeader().setForeground(new Color(255,255,255));
        tableKategori.setRowHeight(25);
        getData();
        getDataDetailPenjualan();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        simpan = new javax.swing.JLabel();
        kembalianInput = new javax.swing.JTextField();
        kembalianLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKategori = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 290, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devpos/Kategori/ImageAssets/lihatTransaksi.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, -1, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devpos/Kategori/ImageAssets/ButtonSimpan.png"))); // NOI18N
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, -1, -1));

        kembalianInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kembalianInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianInputActionPerformed(evt);
            }
        });
        kembalianInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kembalianInputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kembalianInputKeyReleased(evt);
            }
        });
        getContentPane().add(kembalianInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 150, 40));

        kembalianLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kembalianLabel.setText("0");
        getContentPane().add(kembalianLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Kembalian");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("0");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Grand Total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Transaksi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 50, 40, 50));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 290, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Pilih Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 140, -1, -1));

        tableKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "testing", "40", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Umur", "Pekerjaan"
            }
        ));
        tableKategori.setFocusable(false);
        tableKategori.setGridColor(new java.awt.Color(0, 153, 255));
        tableKategori.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableKategori.setRowHeight(25);
        tableKategori.setSelectionBackground(new java.awt.Color(0, 102, 255));
        tableKategori.setShowVerticalLines(false);
        tableKategori.getTableHeader().setReorderingAllowed(false);
        tableKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKategori);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 200, 400, 390));

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "testing", "40", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Umur", "Pekerjaan"
            }
        ));
        tableTransaksi.setFocusable(false);
        tableTransaksi.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableTransaksi.setRowHeight(25);
        tableTransaksi.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tableTransaksi.setShowVerticalLines(false);
        tableTransaksi.getTableHeader().setReorderingAllowed(false);
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableTransaksi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 600, 230));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devpos/Kategori/ImageAssets/transaksi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -80, 1620, 1050));

        setSize(new java.awt.Dimension(1453, 938));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tableKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKategoriMouseClicked
        // TODO add your handling code here:
        int baris = tableKategori.getSelectedRow();
        String globalId = tableKategori.getValueAt(baris, 0).toString();
        String inputName = tableKategori.getValueAt(baris, 1).toString();
        String inputHarga = tableKategori.getValueAt(baris, 2).toString();
        Transaksi.createDetailPenjualan(inputName,inputHarga,"1",globalId);
        getDataDetailPenjualan();
//        new InfoEditDelete().setVisible(true);
        
    }//GEN-LAST:event_tableKategoriMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
        new KategoriView().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        // TODO add your handling code here:
        int baris = tableTransaksi.getSelectedRow();
        String globalIdEdit = tableTransaksi.getValueAt(baris, 0).toString();
        String inputNameEdit = tableTransaksi.getValueAt(baris, 1).toString();
        String inputHargaEdit = tableTransaksi.getValueAt(baris, 2).toString();

        Transaksi.editDetailPenjualan(inputNameEdit,inputHargaEdit,"1",globalIdEdit);
        getDataDetailPenjualan();
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void kembalianInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianInputActionPerformed
        // TODO add your handling code here:
        int baris = tableKategori.getSelectedRow();
        globalId = tableKategori.getValueAt(baris, 0).toString();
        inputNameEdit = tableKategori.getValueAt(baris, 1).toString();
        inputHargaEdit = tableKategori.getValueAt(baris, 2).toString();
    }//GEN-LAST:event_kembalianInputActionPerformed

    private void kembalianInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kembalianInputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianInputKeyPressed

    private void kembalianInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kembalianInputKeyReleased
        // TODO add your handling code here:
        
        int totalKembalian=Integer.parseInt(kembalianInput.getText()) - Integer.parseInt(jLabel7.getText());
        if(totalKembalian>0){
            kembalianLabel.setText(Integer.toString(totalKembalian));
        }else{
            kembalianLabel.setText("0");
        }
    }//GEN-LAST:event_kembalianInputKeyReleased

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
        String grandTotal = jLabel7.getText();
        String kembalianLabelVar = kembalianLabel.getText();
        String kembalianInputVar = kembalianInput.getText();
  
            int g = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Menambah ?", "Tambah?", JOptionPane.YES_NO_OPTION);

            if(g == 0){
                String Info = Transaksi.createPenjualan(kembalianLabelVar,grandTotal, kembalianInputVar,"");
                JOptionPane.showMessageDialog(null, Info);
            }
        
//        inputName.setText("");
        kembalianLabel.setText("0");
        kembalianInput.setText("0");
        getDataDetailPenjualan();
    }//GEN-LAST:event_simpanMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new BarangView().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new TransaksiList().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TransaksiView().setVisible(true);
        });
    }
    public void disposeView(){
    setDefaultCloseOperation(TransaksiView.DISPOSE_ON_CLOSE);
    }
    public static void getData(){
    tableKategori.setModel(new javax.swing.table.DefaultTableModel(
            Barang.listData(),
            new String [] {
                "Kode Barang", "Nama Barang","Harga Barang"}
        ){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }
    public static void getDataDetailPenjualan(){
    tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            Transaksi.listDataDetailPenjualan("SELECT id_barang, name,harga,qty,id FROM detail_penjualan where id_transaksi is null"),
            new String [] {
                "Kode Barang", "Nama Barang","Harga Barang","Jumlah","Total"}
        ){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    String[][] listData = Transaksi.listDataDetailPenjualan(" SELECT id_barang, name,harga,qty,id FROM detail_penjualan where id_transaksi is null");
         int dataGrand = 0;
        System.out.println(Arrays.deepToString(listData));
        
        for (int i = 0; i < listData.length; i++) {
            dataGrand += Integer.parseInt(listData[i][4]);
        }
        
        jLabel7.setText(Integer.toString(dataGrand));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kembalianInput;
    private javax.swing.JLabel kembalianLabel;
    private javax.swing.JLabel simpan;
    public static javax.swing.JTable tableKategori;
    public static javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
